/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#ff791a",
        "primary-dark": "#e66a12", 
        "primary-hover": "#e66a15",
        "secondary": "#0B3A66",
        "secondary-light": "#15538b",
        "background-light": "#f8f7f5",
        "background-dark": "#23170f",
        "surface-light": "#ffffff",
        "surface-dark": "#2d1f16",
        "text-subtle": "#6b7280",
        "navy": {
            DEFAULT: "#0B3A66",
            light: "#164B80",
        },
        "surface-dim": "#edd5ca",
        "inverse-primary": "#ffb68e",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "tertiary-container": "#00aaf4",
        "secondary-fixed-dim": "#a4c9fd",
        "inverse-on-surface": "#ffede5",
        "tertiary-fixed": "#cae6ff",
        "on-primary-fixed": "#331200",
        "on-secondary-fixed-variant": "#1f4875",
        "on-background": "#251912",
        "outline": "#8c7264",
        "surface-container-high": "#fbe3d8",
        "on-surface-variant": "#584236",
        "on-secondary-fixed": "#001c38",
        "surface": "#fff8f6",
        "on-tertiary-fixed": "#001e2f",
        "on-tertiary": "#ffffff",
        "tertiary": "#006492",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#ffb68e",
        "on-primary-fixed-variant": "#763300",
        "surface-tint": "#9b4500",
        "secondary-fixed": "#d3e4ff",
        "outline-variant": "#e0c0b0",
        "secondary-container": "#a4c9fd",
        "error": "#ba1a1a",
        "inverse-surface": "#3b2d26",
        "surface-variant": "#f5ded3",
        "on-surface": "#251912",
        "on-tertiary-fixed-variant": "#004b6f",
        "on-primary-container": "#5e2700",
        "on-secondary": "#ffffff",
        "background": "#fff8f6",
        "on-secondary-container": "#2d5481",
        "surface-container": "#ffeae0",
        "surface-container-highest": "#f5ded3",
        "tertiary-fixed-dim": "#8bceff",
        "surface-container-low": "#fff1eb",
        "on-error-container": "#93000a",
        "primary-container": "#ff7A18",
        "surface-bright": "#fff8f6",
        "primary-fixed": "#ffdbca",
        "on-tertiary-container": "#003b58"
      },
      fontFamily: {
        "display": ["Inter", "sans-serif"],
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "mono": ["Courier Prime", "monospace"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem", 
        "lg": "0.5rem", 
        "xl": "0.75rem", 
        "2xl": "1rem", 
        "3xl": "1.5rem",
        "4xl": "2rem",
        "full": "9999px"
      },
      boxShadow: {
        "premium": "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
        "premium-hover": "0 25px 30px -5px rgba(0, 0, 0, 0.15), 0 15px 15px -5px rgba(0, 0, 0, 0.1)",
        "primary": "0 10px 15px -3px rgba(255, 121, 26, 0.3)",
        "secondary": "0 10px 15px -3px rgba(11, 58, 102, 0.3)",
      }
    },
  },
  plugins: [],
}
